version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    restart: always

  db:
    image: postgres:14
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      # Override DATABASE_HOST to ensure it uses the Docker service name
      - POSTGRES_SERVER=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

volumes:
  postgres_data:
