# BioSample checklist
{
    "organism.taxon_id": "tax_id",
    "organism.culture_or_strain_id": "culture_or_strain_id",
    "specimen_voucer": "specimen_voucher",
    "identified_by": "identified_by",
    "lifestage": "lifestage",
    "sex": "sex",
    "organism_part": "organism part",
    "region_and_locality": "geographic location (region and locality)",
    "country_or_sea": "geographic location (country and/or sea)",
    "latitude": "geographic location (latitude)",
    "longitude": "geographic location (longitude)",
    "elevation": "elevation",
    "depth": "depth",
    "habitat": "habitat",
    "collection_method": "sample collection method",
    "collection_date": "collection date",
    "collected_by": "collected_by",
    "collecting_institution": "collecting institution",
    "sample_name": "alias",
    "specimen_id": "specimen_id",
    "title": "title",
    "sample_same_as": "sample same as",
    "sample_derived_from": "sample derived from",
    "tolid": "tolid",
    "project_name": "project name"
}

 # Unmapped:
[
    "organism.scientific_name",
    "organism.genus",
    "organism.species",
    "organism.family",
    "organism.order_or_group",
    "organism.class",
    "organism.phylum",
    "organism.authority",
    "organism.common_name",
    "organism.atol_scientific_name",
    "organism.organism_grouping_key",
    "organism.tax_string",
    "infraspecific_epithet",
    "voucher_institution",
    "specimen_custodian",
    "sample_custodian",
    "indigenous_location",
    "collection_permit",
    "sample_submission",
    "sample_submission_date",
    "data_context",
    "bioplatforma_project_code",
    "bpa_initiative",
    "bioplatforma_project_id",
    "bioplatforma_project_url",
    "bioplatforma_project_description",
    "preservation_method",
    "preservation_temperature",
    "biosample_acctession",
    "project_lead",
    "project_collaborators"
]
 # Experiment SRA schema
{
    "design_description": "design_description",
    "bpa_library_id": "alias",
    "library_strategy": "library_strategy",
    "library_source": "library_source",
    "insert_size": "insert_size",
    "library_construction_protocol": "library_construction_protocol",
    "library_selection": "library_selection",
    "library_layout": "library_layout",
    "instrument_model": "instrument_model",
    "platform": "platform",
}


# Unmapped:
[
    "biosample_accession",
    "material_extracted_by",
    "material_extraction_date",
    "library_prepared_by",
    "library_prepared_date",
    "sequencing_kit",
    "flowcell_type",
    "base_caller_model",
    "bpa_package_id",
    "data_owner",
    "extraction_method",
    "nucleid_acid_treatment",
    "extraction_protocol_DOI",
    "nucleic_acid_conc",
    "nucleic_acid_volume",
    "GAL",
    "sample_access_date"
]
 # Run SRA schema
{
    "bpa_dataset_id": "alias",
    "file_name": "file_name",
    "file_format": "file_format",
}

# Unmapped:
[
    "bpa_package_id",
    "file_checksum",
    "file_submission_date",
    "bioplatforms_url",
    "reads_access_date",
    "sra_run_accession",
    "run_read_count",
    "run_base_count"
]

# Assembly ENA schema
{
    "sra_study_accession": "STUDY",
    "sra_sample_accession": "SAMPLE",
    "assembly_name": "ASSEMBLYNAME",
    "assembly_type": "ASSEMBLYTYPE",
    "assembly_description": "DESCRIPTION",
    "assembly_program": "PROGRAM",
    "assembly_platform": "PLATFORM",
    "coverage": "COVERAGE",
    "mingaplength": "MINGAPLENGTH",
    "total_length": "total-length",
    "scaffold_count": "scaffold-count",
    "scaffold_n50": "n50",
    "contig_count": "count-contig",
    "molecule_type": "MOLECULETYPE",
    "composite_runs": "RUN_REF"
}

# Unmapped:
[
    "assembly_accession",
    "alt_hap_accession",
    "assembly_level",
    "gap_count",
    "longest_scaffold",
    "chromosome_count",
    "primary_qv",
    "alt_qv",
    "combined_qv",
    "primary_kmer",
    "alt_kmer",
    "combined_kmer",
    "busco_c",
    "busco_string",
    "busco_ref",
    "perc_assem",
    "sex_chromosomes",
    "mito_size",
    "plastid_size",
    "contact_map_image_path",
    "assembly_pipeline",
    "assembly_pipeline_ver",
    "assembly_pipeline_link",
    "decontamination_pipeline",
    "decontamination_pipeline_ver",
    "decontamination_pipeline_link",
    "contact_map_pipeline",
    "contact_map_pipeline_ver",
    "contact_map_pipeline_link",
    "curation_pipeline",
    "curation_pipeline_ver",
    "curation_pipeline_link",
    "blob_tk_pipeline",
    "blob_tk_pipeline_ver",
    "blob_tk_pipeline_link",
    "read_mapping_pipeline",
    "read_mapping_pipeline_ver",
    "read_mapping_pipeline_link",
    "treeval_pipeline",
    "treeval_pipeline_ver",
    "treeval_pipeline_link",
    "BEDTools_version",
    "BLAST_version",
    "BUSCO_version",
    "bwamem2_version",
    "Cooler_version",
    "DIAMOND_version",
    "Docker_version",
    "fasta_windows_version",
    "Fastk_version",
    "gawk_version",
    "GeneScopeFK_version",
    "GenomeScope2_version",
    "Gfastats_version",
    "GoaT_CLI_version",
    "Hifiasm_version",
    "HiGlass_version",
    "JBrowse2_version",
    "Juicer_version",
    "JuicerTools_version",
    "MercuryFK_version",
    "Minimap2_version",
    "MitoFinder_version",
    "MitoHiFi_version",
    "MultiQC_version",
    "NCBI_Datasets_version",
    "Nextflow_version",
    "Oatk_version",
    "pigz_version",
    "PretextMap_version",
    "PretextSnapshot_version",
    "purge_dups_version",
    "samtools_version",
    "Seqtk_version",
    "Singularity_version",
    "Uniprot_version",
    "YaHS_version"
]